### ISSUE TITLE
能把百度的导航栏给隐藏掉吗？太占空间了。

### ISSUE THREAD

**Issue by Luxni** [TheRiverElder/Pretty-Baidu-Search-Page#1]
我因为屏幕大小的原因，要把网页缩放到120%才能比较舒适的浏览网页。

然后，百度搜索后，它的导航栏 ：
“网页 资讯 视频 图片 知道 文库 贴吧 采购 地图 更多”

就会刚好的把下面的翻页给挤掉，每次都要滚动下鼠标，难受咧。

**Comment by TheRiverElder** [comment]
已经对脚本进行了升级。现在在右上角的**美化设置**按键的下拉菜单中，可以找到**开关导航**的选项，点击即可显示、隐藏导航栏了。: )
