### ISSUE TITLE
添加新的baidu搜索接口

### ISSUE THREAD

**Issue by Luxni** [TheRiverElder/Pretty-Baidu-Search-Page#2]
在我的firefox里，如果使用firefox的地址栏直接搜索，firefox使用的接口是：
```
www.baidu.com/baidu?*
```
如果是在百度的搜索框中搜索，它使用的是：
```
www.baidu.com/s?*
```
不知道您那边是否也是这样，如果可以的话，希望能在下一版软件中添加，这样就不用我每次手动添加了，感谢感谢。

貌似还有其他的搜索接口，我还没测试，有空我再测试一下吧。

**Comment by TheRiverElder** [comment]
新的脚本已经添加该接口。其它的接口我也试了几个，但是没成功，至少这两个比较常用的是没问题了√
